$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: machine_failure_training_pipeline
experiment_name: machine-failure-training
description: Training Pipeline to predict machine failure using Decision Tree classifier

inputs:
  input:
    type: uri_file
    path: azureml:machine-failure-data@latest
  model_name:
    type: string
    default: machine_failure_prediction_model

outputs:
  train_data:
    type: uri_file
  test_data:
    type: uri_file
  model_info_output_path:
    type: uri_file

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      python prep.py 
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:machine-failure-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.input}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    name: sweep_job
    display_name: sweep-job
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: uri_folder
    sampling_algorithm: random
    trial: ./train.yml
    search_space:
      criterion:
        type: choice
        values: ["gini", "entropy"]
      max_depth:
        type: choice
        values: [1, 3, 5, 10]
      model_type:
        type: choice
        values: ["decision_tree"]
    objective:
      goal: maximize
      primary_metric: Accuracy
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    name: register_model
    display_name: register-model
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:machine-failure-train-env@latest
    inputs:
      model_name: ${{parent.inputs.model_name}}
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
